### PR TITLE
adding reboot boost icon

### PR DESCRIPTION
**Pull request by clarkenciel**
Demo:
reboot

### CODE REVIEW

**Comment by jemus42** [comment]
Awesome \o/

**Comment by clarkenciel** [comment]
given https://github.com/Chronister/mastodon/pull/4 I'm going to update this to put my css changes in the custom file

**Comment by nightpool** [comment]
Not sure I get what the symbol is supposed to be? Am I missing something?

**Review by nightpool — CHANGES_REQUESTED** [review]
make sure to use `git rebase -i` to remove your merge commits!

**Comment by clarkenciel** [comment]
@nightpool noted on the rebase comment. Is that something I can aply at this point?

The icon is a reference to a very "computer" television show from the mid-to-late 90s https://en.wikipedia.org/wiki/ReBoot

**Comment by nightpool** [comment]
I get exactly zero references ever :(

**Comment by clarkenciel** [comment]
To be fair I'm not sure how widely known the show was, but I've seen it pop in conversations on cybre. That being said I'm happy to have this change opened up to the community.

**Comment by clarkenciel** [comment]
okay trying to remove the merge stuff made this worse so i'm going to close this and try again on a clean fork

**Pull request closed without merging**
